/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Step_3;

/**
 *
 * @author micsg
 */
public class BinarySearchTree extends javax.swing.JFrame {

    /**
     * Creates new form BinarySearchTree
     */
    public BinarySearchTree() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inorderSearch = new javax.swing.JButton();
        preOrderSearch = new javax.swing.JButton();
        postOrderSearch = new javax.swing.JButton();
        backToProjects = new javax.swing.JButton();
        backToTeamMember = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inorderSearch.setText("InOrder");
        inorderSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inorderSearchMouseClicked(evt);
            }
        });

        preOrderSearch.setText("PreOrder");
        preOrderSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                preOrderSearchMouseClicked(evt);
            }
        });
        preOrderSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preOrderSearchActionPerformed(evt);
            }
        });

        postOrderSearch.setText("PostOrder");
        postOrderSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postOrderSearchMouseClicked(evt);
            }
        });

        backToProjects.setText(" Projects");
        backToProjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToProjectsMouseClicked(evt);
            }
        });
        backToProjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToProjectsActionPerformed(evt);
            }
        });

        backToTeamMember.setText("TeamMembers");
        backToTeamMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToTeamMemberMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backToProjects)
                .addGap(18, 18, 18)
                .addComponent(backToTeamMember)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inorderSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(preOrderSearch)
                        .addGap(26, 26, 26)
                        .addComponent(postOrderSearch)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inorderSearch)
                    .addComponent(preOrderSearch)
                    .addComponent(postOrderSearch))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backToProjects)
                    .addComponent(backToTeamMember))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // this is the starting point for the traversals still to work out and figure other parts of the code to be able to link it all in to one...
   public String getTraversals() {
        String traversalsDetails = new String();
        if (Company.ProjectsTree != null) {
            traversalsDetails += "in order\n";
            traversalsDetails += Company.ProjectsTree + "\n";
            traversalsDetails += "pre order\n";
            traversalsDetails += Company.ProjectsTree + "\n";
            traversalsDetails += "post order\n";
            traversalsDetails += Company.ProjectsTree + "\n";
            traversalsDetails += "reverse order\n";
            traversalsDetails += Company.ProjectsTree + "\n";
        } else {
            traversalsDetails += "There are no projects to display";
        }
        return traversalsDetails;
    }
   
    private void preOrderSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preOrderSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preOrderSearchActionPerformed

    private void backToProjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToProjectsActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_backToProjectsActionPerformed

    private void backToProjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToProjectsMouseClicked
         this.toBack();
        Company comp = new Company();
        comp.setVisible(true);
        comp.toFront();
        comp.pack();
        comp.setLocationRelativeTo(null);        
        this.dispose(); 
    }//GEN-LAST:event_backToProjectsMouseClicked

    private void backToTeamMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToTeamMemberMouseClicked
        this.toBack();
        TeamMemberTest tmt = new TeamMemberTest();
        tmt.setVisible(true);
        tmt.toFront();
        tmt.pack();
        tmt.setLocationRelativeTo(null);        
        this.dispose(); 
    }//GEN-LAST:event_backToTeamMemberMouseClicked

    private String getInOrder(Company ProjectTree) {
        String inOrderDetails = new String();
        if (ProjectTree != null) {
            inOrderDetails += this.getInOrder(ProjectTree);
            inOrderDetails += ProjectTree + "  ";
            inOrderDetails += this.getInOrder(ProjectTree);
        }
        return inOrderDetails;
    }
    private void inorderSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inorderSearchMouseClicked
            String inOrderDetails = new String();
        if (Company.ProjectsTree != null) {
           // inOrderDetails += this.inorderSearchMouseClicked();
            inOrderDetails += Company.ProjectsTree + "  ";
           // inOrderDetails += this.inorderSearchMouseClicked(Company.ProjectsTree);
        }
       // return inOrderDetails;
    }//GEN-LAST:event_inorderSearchMouseClicked

        private String getPreOrder(Company ProjectTree) {
        String preOrderDetails = new String();
        if (ProjectTree != null) {
            preOrderDetails += ProjectTree + "  ";
            preOrderDetails += this.getPreOrder(ProjectTree);
            preOrderDetails += this.getPreOrder(ProjectTree);
        }
        return preOrderDetails;
    } 
    private void preOrderSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preOrderSearchMouseClicked
        String preOrderDetails = new String();
        if (Company.ProjectsTree != null) {
            preOrderDetails += Company.ProjectsTree  + "  ";
            //preOrderDetails += this.preOrderSearchMouseClicked(ProjectsTree);
            //preOrderDetails += this.preOrderSearchMouseClicked(ProjectsTree);
        }
        //return preOrderDetails;
    }//GEN-LAST:event_preOrderSearchMouseClicked

    private void postOrderSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postOrderSearchMouseClicked
        String postOrderDetails = new String();
        if (Company.ProjectsTree != null) {
            //postOrderDetails += this.getPostOrderSearchMouseClicked(ProjectsTree);
            //postOrderDetails += this.getPostOrderSearchMouseClicked(ProjectsTree);
            postOrderDetails += Company.ProjectsTree + "  ";
        }
       // return postOrderDetails;
    
    }//GEN-LAST:event_postOrderSearchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BinarySearchTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BinarySearchTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BinarySearchTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BinarySearchTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BinarySearchTree().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToProjects;
    private javax.swing.JButton backToTeamMember;
    private javax.swing.JButton inorderSearch;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton postOrderSearch;
    private javax.swing.JButton preOrderSearch;
    // End of variables declaration//GEN-END:variables
}
